export const GET_CITY_WEATHER = 'GET_CITY_WEATHER';
export const CITY_WEATHER_ERROR = 'CITY_WEATHER_ERROR';
export const GET_FORECAST = 'GET_FORECAST';
export const FORECAST_ERROR = 'FORECAST_ERROR';
export const CLEAR_FORECAST = 'CLEAR_FORECAST';
